-- Crear un stream para cada símbolo
CREATE STREAM AAPL_STREAM (symbol STRING, price DOUBLE, timestamp BIGINT) WITH (KAFKA_TOPIC='AAPL', VALUE_FORMAT='JSON');
CREATE STREAM AMZN_STREAM (symbol STRING, price DOUBLE, timestamp BIGINT) WITH (KAFKA_TOPIC='AMZN', VALUE_FORMAT='JSON');
CREATE STREAM BTCUSDT_STREAM (symbol STRING, price DOUBLE, timestamp BIGINT) WITH (KAFKA_TOPIC='BINANCE:BTCUSDT', VALUE_FORMAT='JSON');

-- Calcular el promedio ponderado de precio por símbolo
CREATE TABLE AAPL_AVG_PRICE AS SELECT symbol, AVG(price) AS avg_price FROM AAPL_STREAM WINDOW TUMBLING (SIZE 1 MINUTE) GROUP BY symbol;
CREATE TABLE AMZN_AVG_PRICE AS SELECT symbol, AVG(price) AS avg_price FROM AMZN_STREAM WINDOW TUMBLING (SIZE 1 MINUTE) GROUP BY symbol;
CREATE TABLE BTCUSDT_AVG_PRICE AS SELECT symbol, AVG(price) AS avg_price FROM BTCUSDT_STREAM WINDOW TUMBLING (SIZE 1 MINUTE) GROUP BY symbol;

-- Calcular el número de transacciones por símbolo
CREATE TABLE AAPL_TRANSACTION_COUNT AS SELECT symbol, COUNT(*) AS transaction_count FROM AAPL_STREAM WINDOW TUMBLING (SIZE 1 MINUTE) GROUP BY symbol;
CREATE TABLE AMZN_TRANSACTION_COUNT AS SELECT symbol, COUNT(*) AS transaction_count FROM AMZN_STREAM WINDOW TUMBLING (SIZE 1 MINUTE) GROUP BY symbol;
CREATE TABLE BTCUSDT_TRANSACTION_COUNT AS SELECT symbol, COUNT(*) AS transaction_count FROM BTCUSDT_STREAM WINDOW TUMBLING (SIZE 1 MINUTE) GROUP BY symbol;

-- Encontrar el máximo precio registrado por símbolo
CREATE TABLE AAPL_MAX_PRICE AS SELECT symbol, MAX(price) AS max_price FROM AAPL_STREAM WINDOW TUMBLING (SIZE 1 MINUTE) GROUP BY symbol;
CREATE TABLE AMZN_MAX_PRICE AS SELECT symbol, MAX(price) AS max_price FROM AMZN_STREAM WINDOW TUMBLING (SIZE 1 MINUTE) GROUP BY symbol;
CREATE TABLE BTCUSDT_MAX_PRICE AS SELECT symbol, MAX(price) AS max_price FROM BTCUSDT_STREAM WINDOW TUMBLING (SIZE 1 MINUTE) GROUP BY symbol;

-- Encontrar el mínimo precio registrado por símbolo
CREATE TABLE AAPL_MIN_PRICE AS SELECT symbol, MIN(price) AS min_price FROM AAPL_STREAM WINDOW TUMBLING (SIZE 1 MINUTE) GROUP BY symbol;
CREATE TABLE AMZN_MIN_PRICE AS SELECT symbol, MIN(price) AS min_price FROM AMZN_STREAM WINDOW TUMBLING (SIZE 1 MINUTE) GROUP BY symbol;
CREATE TABLE BTCUSDT_MIN_PRICE AS SELECT symbol, MIN(price) AS min_price FROM BTCUSDT_STREAM WINDOW TUMBLING (SIZE 1 MINUTE) GROUP BY symbol;
